Makefile: use pthread instead of lthread
Otherwise I was getting
Undefined reference to pthread_xxx

Signed-off-by: Daniel Sangorrin <daniel.sangorrin@toshiba.co.jp>